apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: rbalcercik/reko-wl-webapi
  newName: rbalcercik/reko-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20240524.0018 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: rbalcercik/reko-ufe
  newName: rbalcercik/reko-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20240523.2250 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
